config/routes.rb
Rails.application.routes.draw do
  resources :billboards do
    resources :artists 
  end
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
  belongs_to :billboard
end

app/models/billboard.rb
class Billboard < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  before_action :set_artist, only: [:show, :update, :edit, :destroy]
  def index
    @artist = Artist.all
  end

  def show
  end

  def new
    @artist = Artist.new
    render partial: 'form'
  end

  def create
    @aritst = Artist.new(artist_params)
    if @artist.save
      redirect_to billboard_artists_path
    else 
      render :new
    end
  end

  def edit
    render partial: 'form'
  end

  def update
    if @artist.update(artist_params)
      redirect_to billboard_artists_path
    else
      render :new
    end
  end

  def destroy 
    @billboard.destroy 
    redirect_to billboard_artists_path
  end


  private

    def set_artist
      @artist = Artist.find(params[:id])
    end

    def artist_params
      params.require(:billboard).permit(:name)
    end
  end

end

app/controllers/billboards_controller.rb
class BillboardsController < ApplicationController
	before_action :set_billboard, only: [:show, :update, :edit, :destroy]
  def index
    @billboards = Billboard.all
  end

  def show
  end

  def new
    @billboard = Billboard.new
    render partial: 'form'
  end

  def create
    @billboard = Billboard.new(billboard_params)
    if @billboard.save
      redirect_to billboards_path
    else 
      render :new
    end
  end

  def edit
    render partial: 'form'
  end

  def update
    if @billboard.update(billboard_params)
      redirect_to billboards_path
    else
      render :new
    end
  end

  def destroy 
    @billboard.destroy 
    redirect_to billboards_path
  end


  private

    def set_billboard
      @billboard = Billboard.find(params[:id])
    end

    def billboard_params
      params.require(:billboard).permit(:name)
    end
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/billboards_helper.rb
module BillboardsHelper
end

app/views/artists/edit.html.erb
<h1>Artists#edit</h1>
<p>Find me in app/views/artists/edit.html.erb</p>

app/views/artists/index.html.erb
<h1>Artists#index</h1>
<p>Find me in app/views/artists/index.html.erb</p>

app/views/artists/new.html.erb
<h1>Artists#new</h1>
<p>Find me in app/views/artists/new.html.erb</p>

app/views/artists/show.html.erb
<h1>Artists#show</h1>
<p>Find me in app/views/artists/show.html.erb</p>

app/views/billboards/_form.html.erb
<h1><%= @billboard.id ? 'Edit a Billboard' : 'Create a Billboard' %></h1>

<%= form_for @billboard do |f| %>
  <%= f.label :billboard_name %>
  <%= f.text_field :billboard_name, required: true %>

  <%= f.submit %>
<% end %>

app/views/billboards/edit.html.erb
<h1>Billboards#edit</h1>
<p>Find me in app/views/billboards/edit.html.erb</p>

app/views/billboards/index.html.erb
<h1>Billboards</h1>
<hr /> 
<%= link_to 'Add A New Billboard', new_billboard_path %>

<ul>
  <% @billboards.each do |billboard| %>
    <li>
      <%= link_to billboard.billboard_name, billboard %>
    </li>
  <% end %>
</ul>

app/views/billboards/new.html.erb
<h1>Billboards#new</h1>
<p>Find me in app/views/billboards/new.html.erb</p>

app/views/billboards/show.html.erb
<h1>Billboards#show</h1>
<p>Find me in app/views/billboards/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Billboard1</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>